### ISSUE TITLE
Rename links and remove .html

### ISSUE THREAD

**Issue by animysore** [inGenius-Hack/inGenius-Hack.github.io#15]
Rename `/girlgeekshack-page.html` to `/girlgeeks/` 
Rename `/inGenius-page.html` to `/ingenius/`

Remove index.html from links to home page.

**Comment by aryamasinha** [comment]
Not sure how to do this for a static website.

**Comment by animysore** [comment]
@aryamasinha 
I believe this will work. To change the URL of the file `/girlgeeks.html` to `/girlgeeks/`  - 

- Create the folder `/girlgeeks/` 
- Rename the file to `index.html` and place it in `/girlgeeks/`

**Comment by aryamasinha** [comment]
Fixed this issue as well as #17 and added to the existing PR
